### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [Nihisil/google-search-web-application#5]
Hello Alex 👋 , thank you for your effort on the code submission. This is Olivier, whom you met for the first interview, and I am happy to be the reviewer for our code review session. Long, one of our Engineering Leads, was initially scheduled to do this review but he is now on leave so I stepped in to speed up your application.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions/concerns and share your opinions about the implementation (if any) during the process.

If we’re aligned on any issue here and you’d like to correct them, please address the issue using proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. 😇

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding 🤘

**Comment by olivierobert** [comment]
I completed the first round of reviews so have a check 🙏

**Comment by Nihisil** [comment]
Hi Olivier!

Thank you very much for the thoughtful code review, I have learned new things during that.

I addressed all comments, please let me know if you have more questions.

**Comment by olivierobert** [comment]
Thank you for participating in the code review process.

I will now wrap my scorecard for the code challenge. Then, Minda will follow up with you by email.

Have a nice weekend!
