### ISSUE TITLE
Test Coverage in the Red Zone 🔴 

### ISSUE THREAD

**Issue by olivierobert** [Nihisil/google-search-web-application#8]
All the tests pass 👏 

<img width="868" alt="image" src="https://user-images.githubusercontent.com/696529/159947438-ef3db4c1-5bf8-43c8-b9f8-f63232ea815a.png">

However, the test coverage is not uniform enough to be in the yellow or green zone (>90%):

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/696529/159947147-b11f617d-ecf0-4e73-8cdf-a3419f608535.png">

**Comment by Nihisil** [comment]
With excluding some files and adding more unit tests coverage was pushed to the green zone:
![image](https://user-images.githubusercontent.com/475367/160058596-7ba797fb-6d6e-4aad-9e7e-0a0c60e1f263.png)

**Comment by olivierobert** [comment]
That's why it is always good to have a check on test coverage in every PR 💪
