### ISSUE TITLE
[Question] Why removing all keywords upon inserting new ones?

### ISSUE THREAD

**Issue by olivierobert** [Nihisil/google-search-web-application#9]
In the form object `CsvKeywordsForm`, `user.keywords.destroy_all` is called:

https://github.com/Nihisil/google-search-web-application/blob/7df06f6a611567b9190b526550aa56f0a89d400a/app/forms/csv_keywords_form.rb#L25-L30

That seems like a very unexpected side effect 🙃 Note that this side effect is not covered by tests either in https://github.com/Nihisil/google-search-web-application/blob/develop/spec/forms/csv_keywords_form_spec.rb

A user should not lose all their data upon uploading new keywords. So how would you handle this differently?

**Comment by Nihisil** [comment]
Initially, I thought that it would be good to display data only for the latest uploaded keywords, but after your comment, I realized that it was a bad idea :)

I agree that deleting user data without any warning is not a good way to handle this situation, so I removed the code for deleting users' keywords.
